stages:
    - deploy

variables:
    projectName: Prepara.Me - API
    projectType: prepara_api
    projetctFolder: preparame_api
    shouldRunCompose: "false"
    projectPm2Name: api.preparame.homolog.inf.br

deploy_job:
    stage: deploy
    script:
        - echo "Deploying develop branch..."
        - cd /var/www/app/$projetctFolder
        - git checkout .
        - git pull origin develop
        - echo "Publicando $projectName"
        - sed -i 's/\r$//' /var/www/app/$projetctFolder/scripts/deploy.sh
        - chmod +x ./scripts/deploy.sh
        - ./scripts/deploy.sh $projetctFolder $projectPm2Name
        - echo "Finalizando deploy..."
    tags:
        - homolog_sso
    only:
        - develop

deploy_production:
    stage: deploy
    script:
        - echo "Deploying master branch..."
        - cd /var/www/$projetctFolder
        - git checkout .
        - git pull origin master
        - echo "Publicando $projectName"
        - sed -i 's/\r$//' /var/www/$projetctFolder/scripts/deploy.sh
        - chmod +x ./scripts/deploy_prod.sh
        - ./scripts/deploy.sh $projetctFolder $projectPm2Name
        - echo "Finalizando deploy..."
    tags:
        - preparame_prod
    only:
        - master # Run on branches starting with ''
