version: "3"

services:
    database:
        image: postgres
        container_name: database_preparame
        restart: always

        networks:
            - app-network
        ports:
            - 5435:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=admin@01
            - POSTGRES_DB=preparame
        volumes:
            - pgdata:/data/postgres

    app:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: preparame
        restart: always
        ports:
            - 3334:3334
            - 3335:3335
            - 9230:9230
        volumes:
            - .:/usr/app
        networks:
            - app-network
        links:
            - database
        depends_on:
            - database
networks:
  app-network:
    driver: bridge
volumes:
    pgdata:
        driver: local
